2863 review contributing guide
ukaea/PROCESS pull request #2892
Opened 2023-09-06 15:18 UTC by timothy-nunn

I have done a first iteration of how our contributing guide could look. I welcome recommendations/ changes on the new guide. This is heavily influenced by [bluemira's contributing guide](https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/develop/CONTRIBUTING.md).

We will want to consider how changes to the CI (https://github.com/ukaea/PROCESS/issues/2867) will affect this workflow.

2023-09-08 11:03 UTC, jonmaddock requested changes
This is great Tim, thanks for sorting this out; it reads much better and is up-to-date now.

2023-09-08 12:15 UTC, timothy-nunn commented on CONTRIBUTING.md
> +* Discuss the feature with a core PROCESS developer.
There are two ways, we could mention both or choose on:
* Use the emails listed on the README (you, James, Stuart, Michael).
* Create an issue that is a feature request.

Do you have a preference?

2023-09-08 12:20 UTC, timothy-nunn commented on CONTRIBUTING.md
> +* Discuss the feature with a core PROCESS developer.
In fact, I will just link this bullet point back to the top that (now) says 'issue, discussion, email'

2023-09-12 10:12 UTC, jonmaddock approved these changes

2023-09-12 10:12 UTC, jonmaddock commented on CONTRIBUTING.md
> +* Discuss the feature with a core PROCESS developer.
Great!

2023-09-12 10:12 UTC, merged