Refactoring plot_proc.py
ukaea/PROCESS pull request #2979
Opened 2023-10-24 08:04 UTC by clmould

## Description

## Checklist

I confirm that I have completed the following checks:

- [ ] I have justified any large differences in the regression tests caused by this pull request in the comments.
- [ ] I have added new tests where appropriate for the changes I have made.
- [ ] If I have had to change any existing unit or integration tests, I have justified this change in the pull request comments.
- [ ] If I have made documentation changes, I have checked they render correctly.
- [ ] I have added documentation for my change, if appropriate.

2023-12-20 11:38 UTC, oliverfunk commented
From my end, this LGTM!

2023-12-20 15:38 UTC, timothy-nunn requested changes
It looks like a lot of comments, but it basically boils down to:
* Clearing up exactly the types that are contained in the dataclasses and ensuring they have a well-defined API.
* Discussing if consolidation of some of the dataclasses into one unified `ArbitraryGeometry` would make sense (this is not me saying we should do that, it is something for us to discuss)
* Clarifying the names of some functions that are called 'plot...' but dont seem to do any plotting.
* Clarifying the docstrings (types and descriptions) on functions that have lots of returns. This is a complicated sub-package and it will get confusing what does and returns what without more documentation, and I want using this to be as easy as possible for any user of PROCESS.
* Variable naming to, again, aide in clarity and understanding
* Some other minor comments about fudge factors. I see they were in old plot_proc so it might a case of you asking one of the modelers. 

Other than that, the sub-package is laid out well, docstring format is all correct, and plot_proc is looking a lot less busy!

2023-12-20 15:38 UTC, timothy-nunn commented on process/geometry/tfcoil_geometry.py
> +    return_rects.append(
Again, what are all of these rectangles? A comment would be helpful to see what this function is doing

2023-12-20 15:38 UTC, timothy-nunn commented on process/geometry/tfcoil_geometry.py
> +    :rtype: Tuple[List[RectangleGeometry], list]
`:rtype: Tuple[List[RectangleGeometry], List[float]]`? Double check that but I think thats a more descriptive type

2023-12-20 15:38 UTC, timothy-nunn commented on process/geometry/tfcoil_geometry.py
> +    :rtype: Tuple[List[RectangleGeometry], list]
Wait no maybe its a List[List[float]] looking at the code. Need a better description of the types and meanings of the variables involved

2023-12-20 15:38 UTC, timothy-nunn commented on process/geometry/tfcoil_geometry.py
> +    return_verts = [verts1, verts2, verts3, verts4]
Again, what is this?

2023-12-20 15:38 UTC, timothy-nunn commented on process/geometry/utils.py
> +    """Plots half a thin D-section, centred on z = 0
Does this *plot* the D or does it just return the points to be plot? I cant see any plotting logic

2023-12-20 15:38 UTC, timothy-nunn commented on process/geometry/utils.py
> +    :rtype: tuple
`Tuple[List[float], List[float]]`?

2023-12-20 15:38 UTC, timothy-nunn commented on process/geometry/utils.py
> +    :rtype: tuple
Tuple of. Type and description

2023-12-20 15:38 UTC, timothy-nunn commented on process/geometry/utils.py
> +    """Fills the space between two concentric ellipse sectors
I think it more returns the vertices of a shape which, when filled... "fills the space between two concentric ellipse sectors"

2023-12-20 15:38 UTC, timothy-nunn commented on process/geometry/vacuum_vessel_geometry.py
> +class VacuumVesselGeometry:
Same question about ArbitraryGeometry types

2023-12-20 15:38 UTC, timothy-nunn commented on process/geometry/vacuum_vessel_geometry.py
> +    :rtype: DataClass
Same comment as above re type of return

2023-12-20 15:38 UTC, timothy-nunn commented on process/geometry/vacuum_vessel_geometry.py
> +    return VacuumVesselGeometry(
Same comment that these types won't match the type hint

2023-12-20 15:38 UTC, timothy-nunn commented on process/geometry/vacuum_vessel_geometry.py
> +    :rtype: tuple
Tuples of what?

2023-12-20 15:38 UTC, timothy-nunn commented on process/geometry/vacuum_vessel_geometry.py
> +    :rtype: DataClass
Same comment re return type

2023-12-20 16:52 UTC, clmould commented on process/geometry/plasma_geometry.py
> +    else:
It was like this in the source code

2023-12-20 16:52 UTC, clmould commented on process/geometry/plasma_geometry.py
> +    kappa = (1.1 * kappa_95) + 0.04
It was like this in the source code

2024-01-10 15:21 UTC, clmould commented on process/geometry/plasma_geometry.py
> +    else:
I will remove this

2024-01-12 13:14 UTC, timothy-nunn approved these changes
I am happy with the code. Could you maybe comment a before and after from plotproc of the large tokamak just to show nothing has changed?

2024-01-12 13:28 UTC, clmould commented
plot_proc output for large tokamak before:
![plot_proc_2](https://github.com/ukaea/PROCESS/assets/86794332/d6769990-ce7d-40bb-a412-aee53d5d57bb)

after:
![image](https://github.com/ukaea/PROCESS/assets/86794332/b5cf9fb5-dddb-441f-a8d3-7ef305fd49ed)

2024-01-12 13:49 UTC, timothy-nunn commented
Thanks Clair, all looks good to me! Thanks for your work on this!

2024-01-12 14:13 UTC, merged