1824 add solution comparison tool
ukaea/PROCESS pull request #3083
Opened 2024-02-29 16:01 UTC by jonmaddock

2024-03-06 13:51 UTC, jonmaddock commented
It would be better to test this notebook, but also notebooks generally in Process, using the tools in #3091.

2024-03-11 10:43 UTC, jonmaddock commented
@timothy-nunn you reviewed a previous version of this for me [here](https://git.ccfe.ac.uk/process/process/-/merge_requests/883), but I've made quite a few changes that I think improve on that and go beyond it. I'd be grateful for your review, thanks.

2024-03-15 14:55 UTC, timothy-nunn requested changes
Hi Jon, looks good other than a couple typing mistakes, possible (very unlikely) bugs, and a bug with the figure annotation. 

The only thing I wonder about is if we really want to have an implicit `normalising_tag` if `normalise=True` but its not provided? I lean towards explicit in cases like this and the behaviour would be easier to understand if we only normalise if a `normalising_tag` is provided. What are your thoughts on this?

2024-04-25 10:20 UTC, jonmaddock commented on process/io/plot_solutions.py
> +    # TODO Should return ax too?
`plot_solutions()` now returns `fig, df`.

2024-04-26 07:50 UTC, jonmaddock commented on process/io/plot_solutions.py
> +    ) / abs(normalising_soln_opt_params_np)
Added a guard for this.

2024-04-26 08:03 UTC, jonmaddock commented on process/io/plot_solutions.py
> +        assert len(objf_list) == 1
For some reason I forgot about that! Corrected.

2024-04-26 08:31 UTC, jonmaddock commented
> Hi Jon, looks good other than a couple typing mistakes, possible (very unlikely) bugs, and a bug with the figure annotation.
> 
> The only thing I wonder about is if we really want to have an implicit `normalising_tag` if `normalise=True` but its not provided? I lean towards explicit in cases like this and the behaviour would be easier to understand if we only normalise if a `normalising_tag` is provided. What are your thoughts on this?

I agree; it would be much better to simplify and just have a `normalising_tag` argument: I'll change this.

2024-04-26 09:30 UTC, jonmaddock commented on process/io/plot_solutions.py
> +        x_axis_label += f", normalised to {normalising_tag}"
Now if `normalising_tag` is `None`, this won't run.

2024-04-26 09:55 UTC, jonmaddock commented on process/io/plot_solutions.py
> +    :param normalising_tag: tag for solution to normalise with, defaults to None
As per your general comment, I've removed the `normalise` argument to avoid this confusion.

2024-04-26 10:00 UTC, jonmaddock commented
Hi Tim, thanks for you patience with this; this is ready for review again.

2024-04-26 10:11 UTC, jonmaddock commented
Apologies, fixing tests.

2024-04-26 11:34 UTC, jonmaddock commented
Ready for review again Tim. Regression tests are failing due to adding `objf_name` to the MFILE output, which isn't in the reference MFILE.

2024-05-01 13:19 UTC, timothy-nunn commented on process/io/plot_solutions.py
> +        mfile_data[var] = mfile.data[var].get_scan(-1)
This is now done at the top

2024-05-01 13:23 UTC, timothy-nunn approved these changes
Happy with these changes, especially the simplification of turning on/off normalisation. Cheers Jon.

2024-05-01 15:18 UTC, merged