#392 Sauter's formulae for plasma current and geometric parameters.
ukaea/PROCESS pull request #3128
Opened 2024-04-05 11:39 UTC by mkovari

Minor refactor of `culcur` in `physics.py`, as described in #392:
Update docstring.
Rename qpsi in culcur as q95.
Eliminate curhat since it's not necessary.
Test for a range of values of triangularity.

2024-04-05 11:54 UTC, mkovari commented
`E       TypeError: culcur() got an unexpected keyword argument 'qpsi'`
I have renamed `qpsi` in culcur as `q95`.
@timothy-nunn

2024-04-09 10:43 UTC, mkovari commented
See detailed comments in the issue #392.

2024-04-17 08:41 UTC, timothy-nunn requested changes
One minor change for code quality, one question to ensure this change is utilised to its fullest potential

2024-04-17 08:41 UTC, timothy-nunn commented on process/plasma_geometry.py
> +    def Sauter_geometry(self, a, r0, kap, tri):
Even though its a persons name, I think `Sauter` should be lower case

2024-04-17 08:41 UTC, timothy-nunn commented on process/plasma_geometry.py
> +        # icurr = 8 specifies use of the Sauter geometry as well as plasma current.
Will it ever make sense to use Sauter geometry without using the Sauter plasma current?

2024-04-17 14:22 UTC, timothy-nunn commented on process/plasma_geometry.py
> +        # icurr = 8 specifies use of the Sauter geometry as well as plasma current.
Ok. If you make this into a new issue we can discuss it there

2024-04-18 07:50 UTC, merged