Fixed #3150 (winding pack current densoty constraint)
ukaea/PROCESS pull request #3160
Opened 2024-04-25 14:36 UTC by mkovari

Fixed #3150.  
Removed obsolete references to PROCESS Users's Guide.

2024-04-26 13:51 UTC, jonmaddock requested changes
I think there's some indentation that needs correcting. Also, why has an image been put in the examples directory? Perhaps this belongs in the docs?

2024-04-26 13:51 UTC, jonmaddock commented on process/current_drive.py
> +                ITER Physics Design Guidelines: 1989 [IPDG89], N. A. Uckan et al,
Fix indentation please.

2024-04-26 13:51 UTC, jonmaddock commented on process/evaluators.py
> +                :param n: number of variables
Again, fix indentation please.

2024-04-26 14:27 UTC, mkovari commented
The image files plot_proc_1, 2 and 3 must have been put into the examples folder automatically when I ran `pytest`.  Because there were so many modified files I used `git commit -a`, and because I didn't have the examples folder open in VSCode I didn't see they had been changed.  

However, they seem to fit, and since only the new third page is shown in the changes tab, I suppose that the other two pages, plot_proc_1.png and plot_proc_2.png were already there, so I have left it there.

2024-04-26 14:33 UTC, mkovari commented
I have removed extra indentations from six files.

2024-05-03 15:10 UTC, jonmaddock requested changes
Please fixup the changes to comments to eliminate the 2 correcting commits and eliminate churn. The `plot_procX.png` figures should be created by running the `examples.ipynb` notebook, and the resulting pngs displayed in the notebook. Please look at how figure 1 and 2 are being handled by the notebook to match. Thanks!

2024-05-07 14:16 UTC, mkovari commented
The plot_proc figures have nothing to do with this pull request.  They result from Chris's edit.  If the example notebook needs changing it should be done there.  I will delete the unwanted png.

2024-05-09 13:52 UTC, mkovari commented
Unwanted png removed.  Rebased.

2024-05-14 09:56 UTC, mkovari commented
I have fixed the conflict localy, but when I rebased and then tried to force push, I couldn't do it:
```
(env) mkovari@J1714:~/PROCESS$ git push --force
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

2024-06-12 10:11 UTC, timothy-nunn submitted a review, later dismissed

2024-06-12 10:11 UTC, timothy-nunn commented on source/fortran/init_module.f90
> +      !! file:///home/mkumar/process/source/fortran/divertor_ode.f90
Can we just remove this line, that file is long gone

2024-06-12 14:35 UTC, timothy-nunn approved these changes

2024-06-12 14:35 UTC, merged