scan errors and warnings
ukaea/PROCESS pull request #3175
Opened 2024-05-09 12:17 UTC by clmould

## Description

## Checklist

I confirm that I have completed the following checks:

- [ ] I have justified any large differences in the regression tests caused by this pull request in the comments.
- [ ] I have added new tests where appropriate for the changes I have made.
- [ ] If I have had to change any existing unit or integration tests, I have justified this change in the pull request comments.
- [ ] If I have made documentation changes, I have checked they render correctly.
- [ ] I have added documentation for my change, if appropriate.

2024-06-03 16:24 UTC, timothy-nunn requested changes

2024-06-10 09:43 UTC, clmould commented on process/scan.py
> +        nsweep_var_name = nsweep_var_name.decode("utf-8")
This isn't a numpy.ndarray so we cannot use the f2py_string_patch_here

2024-06-10 15:42 UTC, timothy-nunn requested changes

2024-06-10 15:42 UTC, timothy-nunn commented on process/main.py
```suggestion
                caller.call_models(x)
                self.ifail = 6

            final.finalise(self.models, self.ifail)
            self.show_errors()

```

2024-06-12 10:17 UTC, timothy-nunn approved these changes

2024-06-12 10:17 UTC, merged