954 bootstrap current fraction scaling formula for steady state machines
ukaea/PROCESS pull request #3268
Opened 2024-08-06 13:56 UTC by chris-ashe

## Description

## Checklist

I confirm that I have completed the following checks:

- [ ] I have justified any large differences in the regression tests caused by this pull request in the comments.
- [ ] I have added new tests where appropriate for the changes I have made.
- [ ] If I have had to change any existing unit or integration tests, I have justified this change in the pull request comments.
- [ ] If I have made documentation changes, I have checked they render correctly.
- [ ] I have added documentation for my change, if appropriate.

2024-08-06 15:31 UTC, stuartmuldrew requested changes
Minor comment about diamagnetic current options

2024-08-07 12:17 UTC, chris-ashe commented on documentation/proc-pages/physics-models/plasma_current.md
> +| 5 | Sakai, Fujita and Okamoto scaling [^11] -- Set `bscfmax` to the maximum required bootstrap current fraction ($\leq 1$).
The warning about taking the calculated diamagnetic fraction from the calculated bootstrap value has been added

2024-08-08 14:05 UTC, mkovari commented
Thanks - a helpful piece of work.
Does it change the results significantly?

2024-08-09 08:57 UTC, stuartmuldrew approved these changes
Happy with error message addition.

2024-08-13 08:14 UTC, merged