edit examples docs page to recommend running in vscode and clarifying…
ukaea/PROCESS pull request #3310
Opened 2024-09-09 12:52 UTC by clmould

… instructions for using jupyter

## Description

## Checklist

I confirm that I have completed the following checks:

- [ ] I have justified any large differences in the regression tests caused by this pull request in the comments.
- [ ] I have added new tests where appropriate for the changes I have made.
- [ ] If I have had to change any existing unit or integration tests, I have justified this change in the pull request comments.
- [ ] If I have made documentation changes, I have checked they render correctly.
- [ ] I have added documentation for my change, if appropriate.

2024-09-13 13:09 UTC, timothy-nunn requested changes
Hi Clair, nothing wrong with what you have written. However, we should use this as an opportunity to refresh the rest of this page:
1. See my comment
2. Review this section https://github.com/ukaea/PROCESS/pull/3310/files#diff-b207a7cfdd17ae0611cf15fd03945225e1760a7ade29abbcc52d0dfe21f5c2b0R80-R87 to reflect the recent changes with testbook.

2024-09-13 13:09 UTC, timothy-nunn commented on documentation/proc-pages/usage/examples.md
>  <h2>Notebooks in Docker</h2>
This section is outdated now that we have removed the dockerfiles. Could you remove it for me in this PR too?

2024-09-20 08:55 UTC, timothy-nunn requested changes
You have removed the Docker section from `examples/README.md` but not `documentation/proc-pages/usage/examples.md`

2024-09-23 13:38 UTC, clmould commented on documentation/proc-pages/usage/examples.md
>  <h2>Maintaining notebooks and scripts</h2>
I replaced all <h2> with # now

2024-09-24 08:15 UTC, timothy-nunn approved these changes

2024-09-24 08:16 UTC, merged