VV stress under quench model review
ukaea/PROCESS pull request #3366
Opened 2024-10-30 11:04 UTC by ajpearcey

closes #3354

2025-03-11 14:45 UTC, chris-ashe requested changes
Some small corrections first

2025-03-11 14:45 UTC, chris-ashe commented on process/physics.py
> +            * (1.0 + kappa95**2 * (1.0 + 2.0 * triang95**2 - 1.2 * triang95**3))
Please update this part of the docs to discuss the change
 https://ukaea.github.io/PROCESS/physics-models/plasma_current/plasma_current/#2-calculate-the-cylindrical-safety-factor

2025-03-11 14:45 UTC, chris-ashe commented on process/hcpb.py
> +                    "(pump_factor)",
To follow the new style guide the variable should be renamed to something like `f_p_fw_blkt_pump`

2025-03-11 14:45 UTC, chris-ashe commented on process/sctfcoil.py
> +            d_vv=build_variables.dr_vv_shell_thickness,
Another rename needed, `dr` already shows that it is a thickness, so this can be removed from the name. It should also be more explicit if this is only one plate or both of the VV

2025-03-11 14:45 UTC, chris-ashe commented on process/sctfcoil.py
> +    """Lambda Term
Please see the approved docstring style here:https://ukaea.github.io/PROCESS/development/standards/#docstrings

As a bonus can the reference be in IEEE format with a clickable DOI link.

2025-03-11 14:45 UTC, chris-ashe commented on source/fortran/constraint_variables.f90
> +  real(dp) :: fixed_q_factor
For the style guide a better name is probably `q95_fixed`

2025-03-11 14:45 UTC, chris-ashe commented on source/fortran/constraint_variables.f90
> +  !! fixed safet factor q at 95% flux surface
Small spelling error

2025-03-11 14:45 UTC, chris-ashe commented on source/fortran/constraint_variables.f90
> +  integer :: i_use_fixed_q_factor
Again probably best to call `i_q95_fixed` for style guide

2025-03-11 14:45 UTC, chris-ashe commented on process/sctfcoil.py
> +def _theta_factor_integral(ro_vv, ri_vv, rm_vv, h_vv, theta1_vv):
Can the functions please have type hints to be more PEP compliant

2025-03-12 13:16 UTC, ajpearcey commented on process/hcpb.py
> +                    "(pump_factor)",
Updated.

2025-03-12 13:18 UTC, ajpearcey commented on process/sctfcoil.py
> +            d_vv=build_variables.dr_vv_shell_thickness,
Updated. It assumes both sides of the shell of the VV. This is should be clear from the variable description.

2025-03-12 13:18 UTC, ajpearcey commented on source/fortran/constraint_variables.f90
> +  real(dp) :: fixed_q_factor
Updated

2025-03-12 13:18 UTC, ajpearcey commented on source/fortran/constraint_variables.f90
> +  !! fixed safet factor q at 95% flux surface
Fixed.

2025-03-12 13:19 UTC, ajpearcey commented on source/fortran/constraint_variables.f90
> +  integer :: i_use_fixed_q_factor
Updated.

2025-03-12 13:55 UTC, ajpearcey commented on process/physics.py
> +            * (1.0 + kappa95**2 * (1.0 + 2.0 * triang95**2 - 1.2 * triang95**3))
Updated.

2025-03-12 13:56 UTC, ajpearcey commented on process/sctfcoil.py
> +def _theta_factor_integral(ro_vv, ri_vv, rm_vv, h_vv, theta1_vv):
Done.

2025-03-12 13:56 UTC, ajpearcey commented on process/sctfcoil.py
> +    """Lambda Term
Done.

2025-03-13 14:34 UTC, chris-ashe requested changes

2025-03-13 14:34 UTC, chris-ashe commented on process/hcpb.py
> +                * fpump
What is `fpump` in this case

2025-03-13 14:34 UTC, chris-ashe commented on source/fortran/constraint_equations.f90
> +      !! q95_fixed : input real : fixed safet factor q at 95% flux surface
Small spelling error

2025-03-13 14:34 UTC, chris-ashe commented on source/fortran/input.f90
> +               'Switch that allows for fixing q95 only in this constraint')
This description does not make sense in this instance

2025-03-13 14:34 UTC, chris-ashe commented on source/fortran/input.f90
> +               'fixed safet factor q at 95% flux surface')
Small spelling error

2025-03-13 16:28 UTC, ajpearcey commented on source/fortran/input.f90
> +               'Switch that allows for fixing q95 only in this constraint')
Updated.

2025-03-13 16:28 UTC, ajpearcey commented on source/fortran/input.f90
> +               'fixed safet factor q at 95% flux surface')
Done

2025-03-13 16:28 UTC, ajpearcey commented on source/fortran/constraint_equations.f90
> +      !! q95_fixed : input real : fixed safet factor q at 95% flux surface
Done

2025-03-13 16:35 UTC, ajpearcey commented on process/hcpb.py
> +                * fpump
It is the fraction of FW and blanket thermal power required for pumping. It's output for `primary_pumping == 3`.

2025-03-17 11:12 UTC, chris-ashe approved these changes
Happy with changes

2025-03-20 14:34 UTC, merged