3385 update the plasma composition docs to include all new models
ukaea/PROCESS pull request #3386
Opened 2024-11-08 13:52 UTC by chris-ashe

## Description

## Checklist

I confirm that I have completed the following checks:

- [ ] My changes follow the [PROCESS style guide](https://ukaea.github.io/PROCESS/development/standards/)
- [ ] I have justified any large differences in the regression tests caused by this pull request in the comments.
- [ ] I have added new tests where appropriate for the changes I have made.
- [ ] If I have had to change any existing unit or integration tests, I have justified this change in the pull request comments.
- [ ] If I have made documentation changes, I have checked they render correctly.
- [ ] I have added documentation for my change, if appropriate.

2025-01-27 14:10 UTC, j-a-foster requested changes
Just a couple of minor things, otherwise docs all look good.

2025-01-27 14:10 UTC, j-a-foster commented on documentation/proc-pages/physics-models/plasma_composition.md
> +As stated above, the number density fractions for hydrogen (all isotopes) and
This is quite a long sentence, maybe try and split it up?

2025-01-27 14:10 UTC, j-a-foster commented on documentation/proc-pages/physics-models/plasma_composition.md
> +    \mathtt{nd_fuel_ions} | n_{\text{i}} = \frac{\mathtt{znfuel}}{1+f_{\text{3He}}}
This hasn't parsed correctly - the `nd_fuel_ions` has the `f` and `i` as subscripts.

2025-01-28 11:48 UTC, j-a-foster approved these changes
Additions to `constants.f90` are all correct.

2025-01-28 13:13 UTC, timothy-nunn approved these changes
Happy with changes. Just want to check a section with lots of comments has all of them referenced.

2025-01-28 13:13 UTC, timothy-nunn commented on process/physics_functions.py
> +        ** -1.33
Do all of these constants and factors come from the referenced papers?

2025-01-28 13:13 UTC, timothy-nunn commented on process/physics_functions.py
> +        ** -1.33
And `0.62` (rpow)

2025-01-28 13:16 UTC, chris-ashe commented on process/physics_functions.py
> +        ** -1.33
I will be coming back to this when I look at the radiation properly in another PR, was doing it originally with the composition review

2025-01-28 17:24 UTC, timothy-nunn approved these changes

2025-01-29 10:17 UTC, j-a-foster approved these changes
Happy for this to be merged.

2025-01-29 10:29 UTC, merged