Change Variable Names with "/" : Papercut #1722
ukaea/PROCESS pull request #3404
Opened 2024-11-15 11:39 UTC by athoynilimanew

## Description
closes {1722}

Changes Variable names that have "/" in it.

## Checklist

I confirm that I have completed the following checks:

- [ ] My changes follow the [PROCESS style guide](https://ukaea.github.io/PROCESS/development/standards/)
- [ ] I have justified any large differences in the regression tests caused by this pull request in the comments.
- [ ] I have added new tests where appropriate for the changes I have made.
- [ ] If I have had to change any existing unit or integration tests, I have justified this change in the pull request comments.
- [ ] If I have made documentation changes, I have checked they render correctly.
- [ ] I have added documentation for my change, if appropriate.

2024-11-18 13:22 UTC, ajpearcey requested changes

2024-11-18 13:56 UTC, athoynilimanew commented on process/io/plot_scans.py
> +            elif output_name == "pdivtbt_over_qar":
removed.

2024-12-04 08:12 UTC, athoynilimanew commented
> Could you also add the changes to the output variables into `obsolete_variable.py`?

Added.

2024-12-04 09:25 UTC, ajpearcey approved these changes

2024-12-04 15:36 UTC, merged