Add various plotting scripts for plasma profiles and branching ratios
ukaea/PROCESS pull request #3412
Opened 2024-11-29 10:51 UTC by chris-ashe

This pull request includes several new plotting scripts for generating various scientific plots using `bokeh` and `matplotlib`. The changes introduce new visualizations and interactive elements to enhance data representation.

### New Plotting Scripts:

* [`documentation/proc-pages/scripts/plotting_scripts/beam_energy_decay.py`](diffhunk://#diff-c584cc44e982d7f0c6c9d15a49d0edaf7ed75c361854bf67b88a80f423c581b4R1-R48): Added a script to plot a parabolic profile with interactive sliders for plasma center value and profile index.
* [`documentation/proc-pages/scripts/plotting_scripts/deuterium_branching_plot.py`](diffhunk://#diff-5bbcead06b76888c5710bd8d6584aae00d562050d3bcc6343920b46ea7d4e5a8R1-R29): Added a script to plot the deuterium-deuterium branching ratio using `matplotlib`.
* [`documentation/proc-pages/scripts/plotting_scripts/fast_alpha_pressure.py`](diffhunk://#diff-83578272e6aa46f17889b985a8ec0711fbc4e24d000cafb683635daafae4496eR1-R59): Added a script to plot current profiles with interactive sliders for plasma center value.
* [`documentation/proc-pages/scripts/plotting_scripts/plot_pulsed_current.py`](diffhunk://#diff-0a58669c343515c4a806966cea11d8578aef845a4958cc553b8405da4ad06f8dR1-R125): Added a script to plot pulsed current profiles over time using `matplotlib`.
* [`documentation/proc-pages/scripts/plotting_scripts/profile_hastie_current.py`](diffhunk://#diff-6526024f2a0a3d556beb6df064afcb254fb46e9bbd99d505915a92f4c7cb58dbR1-R62): Added a script to plot the PROCESS vs Hastie current profile with interactive sliders for plasma center value and profile index.
* [`documentation/proc-pages/scripts/plotting_scripts/profile_parabolic_gradiant_plot.py`](diffhunk://#diff-6c494179549189e255c2291f1510216fd588a965aff7611dd50ca49fc1af3a48R1-R42): Added a script to plot the parabolic gradient profile with interactive sliders for plasma center value and profile index.
* [`documentation/proc-pages/scripts/plotting_scripts/profile_parabolic_plot.py`](diffhunk://#diff-c584cc44e982d7f0c6c9d15a49d0edaf7ed75c361854bf67b88a80f423c581b4R1-R48): Added a script to plot a parabolic profile with interactive sliders for plasma center value and profile index.
* [`documentation/proc-pages/scripts/plotting_scripts/profile_pedestal_plot.py`](diffhunk://#diff-0b3fa3b6624989956bc25bd4270b0d587d2045c70b2b16af29476940965a81b8R1-R77): Added a script to plot the pedestal profile with multiple interactive sliders for various parameters.
* [`documentation/proc-pages/scripts/plotting_scripts/profile_peng_qbar.py`](diffhunk://#diff-2d8381b0b1afffafb341e7cecaffc690141896d02b106f6fd4ce9dfecad39b55R1-R68): Added a script to plot the average safety factor for PROCESS vs STAR code with interactive sliders for safety factors.## Description

## Checklist

I confirm that I have completed the following checks:

- [ ] My changes follow the [PROCESS style guide](https://ukaea.github.io/PROCESS/development/standards/)
- [ ] I have justified any large differences in the regression tests caused by this pull request in the comments.
- [ ] I have added new tests where appropriate for the changes I have made.
- [ ] If I have had to change any existing unit or integration tests, I have justified this change in the pull request comments.
- [ ] If I have made documentation changes, I have checked they render correctly.
- [ ] I have added documentation for my change, if appropriate.

2024-12-04 11:39 UTC, timothy-nunn requested changes
Why don't all of the scripts (except the matplotlib ones) use `output_file`?

2024-12-04 11:39 UTC, timothy-nunn commented on documentation/proc-pages/scripts/plotting_scripts/beam_energy_decay.py
> +    filename="/PROCESS/profile_parabolic_plot.html",
```suggestion
    filename="profile_parabolic_plot.html",
```

2024-12-04 11:39 UTC, timothy-nunn commented on documentation/proc-pages/scripts/plotting_scripts/fast_alpha_pressure.py
> +y2 = 0.26(0.75 - 0.65) ** 0.5 * (x) ** 2  # Initial data for the second line
```suggestion
y1 = 0.29 * (x) ** 2 * (0.75 - 0.37)
y2 = 0.26 * (0.75 - 0.65) ** 0.5 * (x) ** 2  # Initial data for the second line
```

2024-12-04 16:03 UTC, chris-ashe commented on documentation/proc-pages/scripts/plotting_scripts/plot_pulsed_current.py
> +ax.set_yticklabels([])
Yes

2024-12-04 16:03 UTC, chris-ashe commented on documentation/proc-pages/scripts/plotting_scripts/profile_parabolic_plot.py
> +plot.yaxis.axis_label = r"Density, $$n_e$$"
You need to run the script with at least Bokeh 2.8.0

2024-12-11 10:06 UTC, timothy-nunn requested changes
Pre-commit failure: https://github.com/ukaea/PROCESS/pull/3412/checks#step:5:39

This comment still applies: https://github.com/ukaea/PROCESS/pull/3412#discussion_r1869311849

2024-12-16 09:34 UTC, chris-ashe commented on documentation/proc-pages/scripts/plotting_scripts/profile_pedestal_plot.py
> +Tbeta.js_on_change("value", callback)
Fixed

2024-12-16 14:54 UTC, timothy-nunn approved these changes

2024-12-16 14:54 UTC, merged