Replace maths library with Python libraries
ukaea/PROCESS pull request #3418
Opened 2024-12-11 10:35 UTC by timothy-nunn

Removing some of the maths routines that can be replaced with simple routines from libraries like numpy and scipy.

2024-12-11 10:40 UTC, timothy-nunn commented on process/pfcoil.py
> +        umat, sigma, vmat = svd(gmat)
The changes to PF coil require a bit of explaining. The single value decomposition from scipy returns different results to the maths library implementation. This causes the integration tests to fail, but none of the regression tests.

In some cases, like `test_solv` the values of `ccls` changed, but their sum did not. 
In `test_efc`, the `ccls` values changed (one of the PF coils groups ended up with 0 current!?) but the `ssq` value did not, weirdly, `ssq` is calculated from the `ccls`.

Overall, I suspect this is nothing to worry about, but its worth careful consideration before approving.

2025-02-04 16:43 UTC, jonmaddock requested changes
Great, just the question of the SVD differences. I'm not sure how serious these differences are; it looks correct, but maybe we need to convince ourselves fully.

2025-02-04 16:43 UTC, jonmaddock commented on tests/integration/test_pfcoil_int.py
> +            174.22748790786324,
I'm sure this is intentional, but can you explain why `curpfb` and `curfps` values have been swapped?

2025-02-04 16:43 UTC, jonmaddock commented on tests/integration/test_pfcoil_int.py
> +    )
What's the reason for removing the 4th element?

2025-02-04 16:43 UTC, jonmaddock commented on tests/integration/test_pfcoil_int.py
> +    assert_array_almost_equal(ccls, np.array([-0.069036, 0.488642, 0.080394]))
These are quite different, as you say.

2025-02-04 16:43 UTC, jonmaddock commented on process/pfcoil.py
> +        umat, sigma, vmat = svd(gmat)
I see, this is tricky. There are some quite substantial (to me) differences in the test results; we just need to be happy that this is due to differences in the SVD implementations and not any mistakes in the refactoring. It's particularly strange about the sum and `ssq` values, as you say.

2025-02-04 16:43 UTC, jonmaddock commented on process/pfcoil.py
> -            ccls[i] = 0.0e0
Was this doing anything before? Clutching at straws!

2025-02-05 15:40 UTC, timothy-nunn commented
The SVD differences can be explained as follows. The original SVD implementation does not return a correctly factorised matrix. The following code demonstrates that when attempting to recreate the original matrix (https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svd.html) for the `test_solv`, the outputs do not create a 3x3 matrix of all 2's when running with `OLD=True`, but do when running with `OLD=False` (the new integration test values).

```python
import numpy as np

OLD = True

if OLD:
    U = np.array([
        [-0.81649658, -0.57735027, 0.0],
        [0.40824829, -0.57735027, -0.70710678],
        [0.40824829, -0.57735027, 0.70710678],
    ])
    V = np.array([
        [-0.81649658, -0.57735027, 0.0],
        [0.40824829, -0.57735027, -0.70710678],
        [0.40824829, -0.57735027, 0.70710678],
    ])
    s = np.array([5.1279005e-16, 6.0000000e00, 0.0000000e00])
else:
    U = np.array([
        [-0.57735027, -0.57735027, -0.57735027],
        [-0.57735027, -0.21132487, 0.78867513],
        [-0.57735027, 0.78867513, -0.21132487],
    ])
    V = np.array([
        [-0.57735027, -0.57735027, -0.57735027],
        [0.0, -0.70710678, 0.70710678],
        [0.81649658, -0.40824829, -0.40824829],
    ])
    s = np.array([6.0, 0.0, 0.0])


# reconstruct
sigma = np.zeros((3, 3))
for i in range(3):
    sigma[i, i] = s[i]

a1 = np.dot(U, np.dot(sigma, V))

print(f"Checking {'old' if OLD else 'new'} SVD results")
print("Original matrix was 3x3 all 2's")
print(a1)
```

2025-02-05 16:01 UTC, timothy-nunn commented on tests/integration/test_pfcoil_int.py
> +            174.22748790786324,
Im not sure this is happening anymore

2025-02-05 16:02 UTC, timothy-nunn commented on tests/integration/test_pfcoil_int.py
> +    )
It became 0, I will add it back since its probably correct to do so

2025-02-05 16:02 UTC, timothy-nunn commented on process/pfcoil.py
> -            ccls[i] = 0.0e0
Relic of Fortran

2025-02-07 15:40 UTC, jonmaddock approved these changes

2025-02-12 13:19 UTC, merged