Replace black and flake8 with ruff
ukaea/PROCESS pull request #3424
Opened 2024-12-12 13:24 UTC by timothy-nunn

Update our codebase to use `ruff` as a formatter instead of `black`, and use `ruff` as a linter instead of `flake8`. The benefits of this change are:
- Faster linting and formatting.
- Unification of formatting and linting into one tool.
- Ability to enable future rules (e.g. import sorting) without additional tools.
- Parity with other open-source UKAEA codes like bluemira and PyVMCON.

The downsides could be merge conflicts in the short term.

2024-12-19 16:07 UTC, timothy-nunn commented
Rules that are not going to be implemented but will be papercuts:
NPY, SLF, BLE, B, A, DTZ, EXE, ICN, PIE, RET, PD, PERF, FURB

2025-01-08 15:13 UTC, chris-ashe requested changes
Minor spelling error

2025-01-08 15:13 UTC, chris-ashe commented on documentation/proc-pages/development/pre-commit.md
> +    > git add foo.py # since rufd has modified foo.py
`ruff`

2025-01-08 15:26 UTC, chris-ashe approved these changes
Happy with doc changes

2025-01-08 15:51 UTC, merged